In [1]:
import os
os.getcwd()

'C:\\Users\\Rambabu\\Desktop\\remoteinternship2020\\python'

In [2]:
os.chdir("C:/Users/Rambabu/Desktop/remoteinternship2020/dataset")

In [3]:
os.getcwd()

'C:\\Users\\Rambabu\\Desktop\\remoteinternship2020\\dataset'

In [4]:
import numpy as np
import pandas as pd

In [6]:
data=pd.read_csv("T1.csv")

In [7]:
data

Date/Time  LV ActivePower (kW)  Wind Speed (m/s)  \
0      01 01 2018 00:00           380.047791          5.311336   
1      01 01 2018 00:10           453.769196          5.672167   
2      01 01 2018 00:20           306.376587          5.216037   
3      01 01 2018 00:30           419.645905          5.659674   
4      01 01 2018 00:40           380.650696          5.577941   
...                 ...                  ...               ...   
50525  31 12 2018 23:10          2963.980957         11.404030   
50526  31 12 2018 23:20          1684.353027          7.332648   
50527  31 12 2018 23:30          2201.106934          8.435358   
50528  31 12 2018 23:40          2515.694092          9.421366   
50529  31 12 2018 23:50          2820.466064          9.979332   

       Theoretical_Power_Curve (KWh)  Wind Direction (°)  
0                         416.328908          259.994904  
1                         519.917511          268.641113  
2                         390.900016          272.564789  
3                         516.127569          271.258087  
4                         491.702972          265.674286  
...                              ...                 ...  
50525                    3397.190793           80.502724  
50526                    1173.055771           84.062599  
50527                    1788.284755           84.742500  
50528                    2418.382503           84.297913  
50529                    2779.184096           82.274620  

[50530 rows x 5 columns]

In [9]:
data1=data.drop('Theoretical_Power_Curve (KWh)',axis=1)
x=data1.iloc[0:,0:3].values
x

array([['01 01 2018 00:00', 380.047790527343, 5.31133604049682],
       ['01 01 2018 00:10', 453.76919555664, 5.67216682434082],
       ['01 01 2018 00:20', 306.376586914062, 5.21603679656982],
       ...,
       ['31 12 2018 23:30', 2201.10693359375, 8.43535804748535],
       ['31 12 2018 23:40', 2515.69409179687, 9.42136573791503],
       ['31 12 2018 23:50', 2820.46606445312, 9.97933197021484]],
      dtype=object)

In [17]:
y=data.iloc[0:,2].values
y

array([5.31133604, 5.67216682, 5.2160368 , ..., 8.43535805, 9.42136574,
       9.97933197])

In [20]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)

In [21]:
x_train

array([['10 12 2018 15:10', 480.995300292968, 5.5590181350708],
       ['07 12 2018 09:20', 1396.22802734375, 7.29126977920532],
       ['17 04 2018 07:30', 0.0, 3.48792695999145],
       ...,
       ['03 11 2018 07:00', 3031.63598632812, 11.193799972534098],
       ['09 11 2018 22:00', 730.650085449218, 6.4380950927734295],
       ['20 01 2018 03:00', 3604.44897460937, 14.530890464782699]],
      dtype=object)

In [22]:
y_train

array([ 5.55901814,  7.29126978,  3.48792696, ..., 11.19379997,
        6.43809509, 14.53089046])

In [23]:
x_test

array([['10 12 2018 16:10', 576.656982421875, 5.95249605178833],
       ['05 02 2018 10:30', 1619.3010253906198, 8.13491821289062],
       ['23 12 2018 11:50', 1876.5810546875, 8.20711517333984],
       ...,
       ['22 03 2018 21:50', 667.257080078125, 6.278903007507321],
       ['02 08 2018 14:20', 3473.52294921875, 12.089229583740199],
       ['08 08 2018 00:20', 2343.06396484375, 10.3140296936035]],
      dtype=object)

In [24]:
y_test

array([ 5.95249605,  8.13491821,  8.20711517, ...,  6.27890301,
       12.08922958, 10.31402969])