In [2]:
import os
os.getcwd()

'C:\\Users\\pc\\Desktop\\remote intership 2020\\python codes'

In [3]:
os.chdir("C:\\Users\\pc\\Desktop\\remote intership 2020\\data sets")

In [4]:
os.getcwd()


'C:\\Users\\pc\\Desktop\\remote intership 2020\\data sets'

In [5]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [6]:
data=pd.read_csv('T1.csv')


In [7]:
data

Date/Time  LV ActivePower (kW)  Wind Speed (m/s)  \
0      01 01 2018 00:00           380.047791          5.311336   
1      01 01 2018 00:10           453.769196          5.672167   
2      01 01 2018 00:20           306.376587          5.216037   
3      01 01 2018 00:30           419.645905          5.659674   
4      01 01 2018 00:40           380.650696          5.577941   
...                 ...                  ...               ...   
50525  31 12 2018 23:10          2963.980957         11.404030   
50526  31 12 2018 23:20          1684.353027          7.332648   
50527  31 12 2018 23:30          2201.106934          8.435358   
50528  31 12 2018 23:40          2515.694092          9.421366   
50529  31 12 2018 23:50          2820.466064          9.979332   

       Theoretical_Power_Curve (KWh)  Wind Direction (°)  
0                         416.328908          259.994904  
1                         519.917511          268.641113  
2                         390.900016          272.564789  
3                         516.127569          271.258087  
4                         491.702972          265.674286  
...                              ...                 ...  
50525                    3397.190793           80.502724  
50526                    1173.055771           84.062599  
50527                    1788.284755           84.742500  
50528                    2418.382503           84.297913  
50529                    2779.184096           82.274620  

[50530 rows x 5 columns]

In [8]:
data.drop('Date/Time',axis=1,inplace=True)
data

LV ActivePower (kW)  Wind Speed (m/s)  Theoretical_Power_Curve (KWh)  \
0               380.047791          5.311336                     416.328908   
1               453.769196          5.672167                     519.917511   
2               306.376587          5.216037                     390.900016   
3               419.645905          5.659674                     516.127569   
4               380.650696          5.577941                     491.702972   
...                    ...               ...                            ...   
50525          2963.980957         11.404030                    3397.190793   
50526          1684.353027          7.332648                    1173.055771   
50527          2201.106934          8.435358                    1788.284755   
50528          2515.694092          9.421366                    2418.382503   
50529          2820.466064          9.979332                    2779.184096   

       Wind Direction (°)  
0              259.994904  
1              268.641113  
2              272.564789  
3              271.258087  
4              265.674286  
...                   ...  
50525           80.502724  
50526           84.062599  
50527           84.742500  
50528           84.297913  
50529           82.274620  

[50530 rows x 4 columns]

In [9]:
data.describe()

LV ActivePower (kW)  Wind Speed (m/s)  Theoretical_Power_Curve (KWh)  \
count         50530.000000      50530.000000                   50530.000000   
mean           1307.684332          7.557952                    1492.175463   
std            1312.459242          4.227166                    1368.018238   
min              -2.471405          0.000000                       0.000000   
25%              50.677890          4.201395                     161.328167   
50%             825.838074          7.104594                    1063.776283   
75%            2482.507568         10.300020                    2964.972462   
max            3618.732910         25.206011                    3600.000000   

       Wind Direction (°)  
count        50530.000000  
mean           123.687559  
std             93.443736  
min              0.000000  
25%             49.315437  
50%             73.712978  
75%            201.696720  
max            359.997589

In [10]:
data.isnull().any()

LV ActivePower (kW)              False
Wind Speed (m/s)                 False
Theoretical_Power_Curve (KWh)    False
Wind Direction (°)               False
dtype: bool

In [11]:
data1=data.drop('Theoretical_Power_Curve (KWh)',axis=1)
x=data1.iloc[0:,0:3].values
x

array([[ 380.04779053,    5.31133604,  259.99490356],
       [ 453.76919556,    5.67216682,  268.64111328],
       [ 306.37658691,    5.2160368 ,  272.56478882],
       ...,
       [2201.10693359,    8.43535805,   84.74250031],
       [2515.6940918 ,    9.42136574,   84.2979126 ],
       [2820.46606445,    9.97933197,   82.27462006]])

In [12]:
y=data.iloc[0:,2].values
y

array([ 416.32890782,  519.91751106,  390.90001581, ..., 1788.28475526,
       2418.38250336, 2779.18409628])

In [13]:
from sklearn.preprocessing import MinMaxScaler
m=MinMaxScaler()
x=m.fit_transform(x)
x

array([[0.10563314, 0.21071704, 0.7222129 ],
       [0.1259914 , 0.22503231, 0.74623031],
       [0.08528875, 0.20693623, 0.75712948],
       ...,
       [0.60852085, 0.33465661, 0.23539741],
       [0.69539448, 0.37377457, 0.23416244],
       [0.77955763, 0.3959108 , 0.22854214]])

In [14]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x=sc.fit_transform(x)
x

array([[-0.70679964, -0.53147626,  1.45872479],
       [-0.65062865, -0.44611545,  1.55125422],
       [-0.76293238, -0.55402096,  1.59324434],
       ...,
       [ 0.68073081,  0.20756566, -0.41677961],
       [ 0.92042608,  0.44082298, -0.42153747],
       [ 1.1526428 ,  0.57281963, -0.4431902 ]])

# TRAINING AND TESTING THE MODEL

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)

In [16]:
x_train

array([[-0.6298841 , -0.47288274, -0.61104065],
       [ 0.06746463, -0.06308839, -1.04615108],
       [-0.99637172, -0.9628355 ,  0.52784729],
       ...,
       [ 1.31354076,  0.86012323, -0.63432838],
       [-0.43966314, -0.26492175, -0.54217731],
       [ 1.74998758,  1.64957022,  0.90420909]])

In [17]:
y_train

array([ 486.13884213, 1152.69070387,   50.65948018, ..., 3336.659665  ,
        781.98799626, 3600.        ])

In [18]:
x_test

array([[-0.55699603, -0.37979868, -0.53946612],
       [ 0.23743197,  0.13649137, -0.70790443],
       [ 0.43346287,  0.15357082,  1.3998277 ],
       ...,
       [-0.48796455, -0.30258141,  0.01071719],
       [ 1.65023033,  1.07195273, -1.00636365],
       [ 0.78889298,  0.65199822, -0.67888882]])

In [19]:
y_test

array([ 609.08146942, 1608.17935444, 1650.73919566, ...,  722.1880659 ,
       3535.14867257, 2972.39826913])

In [20]:
from sklearn.linear_model import LinearRegression
mr=LinearRegression()
mr.fit(x_train,y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [21]:
import pickle
pickle.dump(mr,open('decision2.pkl','wb'))

In [22]:
y_pred=mr.predict(x_test)

In [23]:
y_pred

array([ 873.79249174, 1779.68261469, 1843.49487137, ...,  949.14715804,
       3401.54611731, 2501.27839185])

In [24]:
y_test

array([ 609.08146942, 1608.17935444, 1650.73919566, ...,  722.1880659 ,
       3535.14867257, 2972.39826913])